### PR TITLE
[ADD] .travis.yml: Enable CI

### PR DESCRIPTION
**Pull request by moylop260**
- Enable travis ci builds.

### CODE REVIEW

**Comment by moylop260** [comment]
@nhomar 
Please
nhomar

**Comment by nhomar** [comment]
Done @moylop260

**Comment by moylop260** [comment]
@nhomar 
It's done!

Could you merge it?

You will see errors in the log and red build but It will fix in the following WIP PR https://github.com/Vauxoo/docker-ubuntu-base/pull/17/files

**Comment by moylop260** [comment]
@nhomar 
Do you checked my last https://github.com/Vauxoo/runbot/pull/10#issuecomment-220804945?

**Pull request merged**
